steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: schetnaServiceKeyCredential
    integrationFlowId: S0024648617-flow4
    integrationFlowName: S0024648617-flow4
    packageId: CICD
    filePath: S0024648617-flow4.zip

 
