---
general:
  cpiApiServiceKeyCredentialsId: "mygitservicekey"
  integrationFlowId: "S0024648617-flow4"
stages:
  uploadStage:
    enabled: true
  deployStage:
    enabled: true
  integrationTestStage:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "CICD"
    integrationFlowName: "S0024648617-flow4"
  integrationArtifactTriggerIntegrationTest:
    contentType: ""
    messageBodyPath: ""
    integrationFlowServiceKeyCredentialsId: ""